### ISSUE TITLE
Error on Server Name

### ISSUE THREAD

**Issue by khighland** [khibma/ArcGISAdministrationToolkit#6]
I receive this error on the tool when trying to connect to a server in the tool:

I'm using our qualified host name, which supports both HTTP and HTTPS. 

Any ideas why this stopped working?

> ERROR 
> updateParameters Execution Error: Runtime error Traceback (most recent call last): File "P:\PythonScripts\connections\ServerAdminToolkit\Server Admin Toolkit.tbx#StopStartService.UpdateParameters.py", line 4, in File "P:\PythonScripts\connections\ServerAdminToolkit\Server Admin Toolkit.tbx#StopStartService.UpdateParameters.py", line 23, in updateParameters File "P:\PythonScripts\connections\ServerAdminToolkit\Server Admin Toolkit.tbx#StopStartService.UpdateParameters.py", line 74, in getServiceList File "P:\PythonScripts\connections\ServerAdminToolkit\Server Admin Toolkit.tbx#StopStartService.UpdateParameters.py", line 55, in gentoken File "C:\Python27\ArcGIS10.1\Lib\json__init__.py", line 326, in loads return _default_decoder.decode(s) File "C:\Python27\ArcGIS10.1\Lib\json\decoder.py", line 366, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "C:\Python27\ArcGIS10.1\Lib\json\decoder.py", line 384, in raw_decode raise ValueError("No JSON object could be decoded") ValueError: No JSON object could be decoded

**Comment by dkitoko** [comment]
I'm having the same issue on ArcGIS Server 10.2.2 and the host also supports HTTPS.
